src/Entity/EntryInventory.php
<?php

namespace App\Entity;

use App\Repository\EntryInventoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntryInventoryRepository::class)]
#[ORM\HasLifecycleCallbacks]
class EntryInventory
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'entryInventories')]
    private ?User $author = null;

    #[ORM\Column(length: 70, nullable: true)]
    private ?string $reference = null;

    #[ORM\OneToMany(mappedBy: 'inventory', targetEntity: EntryInventoryLine::class)]
    private Collection $entryInventoryLines;

    public function __construct()
    {
        $this->entryInventoryLines = new ArrayCollection();
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initialize()
    {
        if(empty($this->createdAt)){
            $this->createdAt = new \DateTimeImmutable();
        }
    }

    public function getTotalQte()
    {
        $sum = array_reduce($this->entryInventoryLines->toArray(), function ($total, $entryInventoryLine){
            return $total + $entryInventoryLine->getQte();
        }, 0);
        if(count($this->entryInventoryLines) > 0){
            return $sum;
        }else{
            return 0;
        }
    }

    public function getTotalAmount()
    {
        $sum = array_reduce($this->entryInventoryLines->toArray(), function ($total, $entryInventoryLine){
            return $total + ($entryInventoryLine->getQte()*$entryInventoryLine->getProduct()->getSalePrice());
        }, 0);
        if(count($this->entryInventoryLines) > 0){
            return $sum;
        }else{
            return 0;
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(?string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    /**
     * @return Collection<int, EntryInventoryLine>
     */
    public function getEntryInventoryLines(): Collection
    {
        return $this->entryInventoryLines;
    }

    public function addEntryInventoryLine(EntryInventoryLine $entryInventoryLine): static
    {
        if (!$this->entryInventoryLines->contains($entryInventoryLine)) {
            $this->entryInventoryLines->add($entryInventoryLine);
            $entryInventoryLine->setInventory($this);
        }

        return $this;
    }

    public function removeEntryInventoryLine(EntryInventoryLine $entryInventoryLine): static
    {
        if ($this->entryInventoryLines->removeElement($entryInventoryLine)) {
            // set the owning side to null (unless already changed)
            if ($entryInventoryLine->getInventory() === $this) {
                $entryInventoryLine->setInventory(null);
            }
        }

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use function Symfony\Component\Form\remove;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[Vich\Uploadable]
#[ORM\HasLifecycleCallbacks]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message:"Le nom de produit  est obligatoire")]
    #[Assert\Length(min: 2,max: 255,minMessage: "Le nom doit être supérieur à 2 caractères", maxMessage: "Le nom doit être inférieur à 255 caractères")]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Assert\NotBlank(message:"La description du produit  est obligatoire")]
    private ?string $description = null;

    #[Vich\UploadableField(mapping: 'products', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $brandName = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message:"Le prix de vente du produit est obligatoire")]
    private ?int $salePrice = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message:"L'unité du produit est obligatoire")]
    private ?string $unit = null;

    #[ORM\Column(nullable: true)]
    #[Assert\NotBlank(message:"Le quantité seuil  du produit est obligatoire")]
    private ?int $minQte = null;

    #[ORM\Column(nullable: true)]
    #[Assert\NotBlank(message:"Le quantité initial disponible en stcok est obligatoire")]
    private ?int $initQte = null;

    #[ORM\Column(length: 55, nullable: true)]
    #[Assert\NotBlank(message:"Le code bar du produit est obligatoire")]
    private ?string $codeBar = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[Assert\NotBlank(message:"Le categorie (rayonnage) du produit est obligatoire")]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?User $author = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;


    #[ORM\OneToMany(mappedBy: 'product', targetEntity: OrderLine::class)]
    private Collection $orderLines;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: SaleLine::class)]
    private Collection $saleLines;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: EntryInventoryLine::class)]
    private Collection $entryInventoryLines;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: OutInventoryLine::class)]
    private Collection $outInventoryLines;

    public function __construct()
    {
        $this->saleLines = new ArrayCollection();
        $this->orderLines = new ArrayCollection();
        $this->entryInventoryLines = new ArrayCollection();
        $this->outInventoryLines = new ArrayCollection();
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initialize()
    {
        if(empty($this->createdAt)){
            $this->createdAt = new \DateTimeImmutable();
        }
        $this->updatedAt = new  \DateTimeImmutable();
    }

    public function getSaleQte()
    {
        $sum = array_reduce($this->saleLines->toArray(), function ($total, $saleLine){
            return $total + ($saleLine->getQte());
        }, 0);
        if(count($this->saleLines)>0){
            return $sum;
        }else{
            return 0;
        }
    }

    public function getOutStockQte()
    {
        $sum = array_reduce($this->outInventoryLines->toArray(), function ($total, $outInventoryLine){
            return $total + ($outInventoryLine->getQte());
        }, 0);
        if(count($this->outInventoryLines)>0){
            return $sum;
        }else{
            return 0;
        }
    }

    public function getInStockQte()
    {
        $sum = array_reduce($this->entryInventoryLines->toArray(), function ($total, $entryInventoryLine){
            return $total + ($entryInventoryLine->getQte());
        }, 0);
        if(count($this->entryInventoryLines)>0){
            return $sum;
        }else{
            return 0;
        }
    }

    public function getStockQte()
    {
        $sum = $this->initQte + $this->getInStockQte() - $this->getOutStockQte() - $this->getSaleQte();
        return $sum;
    }

    public function getStockValue()
    {
        return $this->getStockQte()*$this->salePrice;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName(): string
    {
        return $this->getName()." Fabriqué par :".$this->getBrandName();
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): static
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getBrandName(): ?string
    {
        return $this->brandName;
    }

    public function setBrandName(?string $brandName): static
    {
        $this->brandName = $brandName;

        return $this;
    }

    public function getSalePrice(): ?int
    {
        return $this->salePrice;
    }

    public function setSalePrice(?int $salePrice): static
    {
        $this->salePrice = $salePrice;

        return $this;
    }

    public function getUnit(): ?string
    {
        return $this->unit;
    }

    public function setUnit(?string $unit): static
    {
        $this->unit = $unit;

        return $this;
    }

    public function getMinQte(): ?int
    {
        return $this->minQte;
    }

    public function setMinQte(?int $minQte): static
    {
        $this->minQte = $minQte;

        return $this;
    }

    public function getInitQte(): ?int
    {
        return $this->initQte;
    }

    public function setInitQte(?int $initQte): static
    {
        $this->initQte = $initQte;

        return $this;
    }

    public function getCodeBar(): ?string
    {
        return $this->codeBar;
    }

    public function setCodeBar(?string $codeBar): static
    {
        $this->codeBar = $codeBar;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, SaleLine>
     */
    public function getSaleLines(): Collection
    {
        return $this->saleLines;
    }

    public function addSaleLine(SaleLine $saleLine): static
    {
        if (!$this->saleLines->contains($saleLine)) {
            $this->saleLines->add($saleLine);
            $saleLine->setProduct($this);
        }

        return $this;
    }

    public function removeSaleLine(SaleLine $saleLine): static
    {
        if ($this->saleLines->removeElement($saleLine)) {
            // set the owning side to null (unless already changed)
            if ($saleLine->getProduct() === $this) {
                $saleLine->setProduct(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->name; // Adjust this based on your entity's properties
    }

    /**
     * @return Collection<int, OrderLine>
     */
    public function getOrderLines(): Collection
    {
        return $this->orderLines;
    }

    public function addOrderLine(OrderLine $orderLine): static
    {
        if (!$this->orderLines->contains($orderLine)) {
            $this->orderLines->add($orderLine);
            $orderLine->setProduct($this);
        }

        return $this;
    }

    public function removeOrderLine(OrderLine $orderLine): static
    {
        if ($this->orderLines->removeElement($orderLine)) {
            // set the owning side to null (unless already changed)
            if ($orderLine->getProduct() === $this) {
                $orderLine->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, EntryInventoryLine>
     */

src/Controller/EntryInventoryController.php
<?php

namespace App\Controller;

use App\Entity\EntryInventory;
use App\Form\EntryInventoryType;
use App\Repository\EntryInventoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EntryInventoryController extends AbstractController
{
    #[Route('/entry/inventory', name: 'entry_inventory')]
    public function index(EntryInventoryRepository $repository): Response
    {
        $data = $repository->findBy([], ['createdAt' => 'DESC'], null, null);
        return $this->render('entry_inventory/index.html.twig', [
            'data' => $data,
        ]);
    }

    #[Route('/entry/inventory/add', name: 'entry_inventory_add')]
    public function add(EntityManagerInterface $manager, Request $request, EntryInventoryRepository $repository): Response
    {
        $entryInventory = new EntryInventory();
        $form = $this->createForm(EntryInventoryType::class, $entryInventory);
        $form->handleRequest($request);
        $next = $repository->count([])+1;
        if($form->isSubmitted() && $form->isValid()){
            foreach($entryInventory->getEntryInventoryLines() as $entryInventoryLine) {
                $entryInventoryLine->setInventory($entryInventory);
                $manager->persist($entryInventoryLine);
            }
            $entryInventory->setAuthor($this->getUser())
                ->setReference('INSTOCK-'.$next)
            ;
            $manager->persist($entryInventory);
            $manager->flush();

            $this->addFlash('success', "L'entrée de stock de reférence <strong>{$entryInventory->getReference()}</strong> est bien enregistrer");

            /*$session->clear();*/
            return $this->redirectToRoute('entry_inventory');
        }
        return $this->render('entry_inventory/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/entry/inventory/{id}', name: 'entry_inventory_edit')]
    public function edit(EntityManagerInterface $manager, Request $request, EntryInventory $entryInventory): Response
    {
        $form = $this->createForm(EntryInventoryType::class, $entryInventory);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            foreach($entryInventory->getEntryInventoryLines() as $entryInventoryLine) {
                $entryInventoryLine->setInventory($entryInventory);
                $manager->persist($entryInventoryLine);
            }
            $entryInventory->setAuthor($this->getUser());
            $manager->persist($entryInventory);
            $manager->flush();

            $this->addFlash('success', "L'entrée de stock de reférence <strong>{$entryInventory->getReference()}</strong> est bien modifier");

            /*$session->clear();*/
            return $this->redirectToRoute('entry_inventory');
        }
        return $this->render('entry_inventory/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/entry/inventory/{id}/delete', name: 'entry_inventory_delete')]
    public function remove(EntityManagerInterface $manager, EntryInventory $entryInventory): Response
    {
        $this->addFlash('success', "L'inventaire de sortie <strong>{$entryInventory->getReference()}</strong> a bien été supprimer");
        $manager->remove($entryInventory);
        $manager->flush();
        return $this->redirectToRoute('entry_inventory');
    }

    #[Route('/entry/inventory/{id}/show', name: 'entry_inventory_show')]
    public function show(EntryInventory $entryInventory): Response
    {
        return $this->render('entry_inventory/show.html.twig', [
            'entryInventory' => $entryInventory,
        ]);
    }
}

templates/entry_inventory/_collection.html.twig
{% block _entry_inventory_entryInventoryLines_widget %}
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-bordered table-hover mg-b-0">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Code Bar</th>
                    <th>Nom du produit</th>
                    <th>Quantite</th>
                    <th class="text-right">
                        <button class="btn btn-primary bd-0" id="add-entryInventoryLine" type="button">Ajouter un produit</button>
                        <input type="hidden" id="widgets-counter" value="0">
                    </th>
                </tr>
                </thead>
                <tbody id="entryInventoryLine">
                {{ form_widget(form) }}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block _entry_inventory_entryInventoryLines_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _entry_inventory_entryInventoryLines_entry_widget %}
    {#<tr>
        <th colspan="7">{{ form_errors(form) }}</th>
    </tr>#}
    <tr class="entry-inventory-line" id="block_{{id}}">
        <th scope="row">{{ id }}</th>
        <td class="code_bar">{{ form_widget(form.codeBar, {'attr':{'class': 'input-code-bar'}}) }}</td>
        <td>{{ form_widget(form.product) }}</td>
        <td>{{ form_widget(form.qte) }}</td>
        <td class="text-right">
            <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-outline-danger btn-icon">
                <div>
                    <i class="fa fa-trash-o"></i>
                </div>
            </button>
        </td>
    </tr>
{% endblock %}

templates/entry_inventory/_form.html.twig
{% form_theme form 'entry_inventory/_collection.html.twig' %}

{{ form_start(form) }}
<div class="row mg-b-25">
    {#<div class="col-lg-12">{{ form_row(form.reference) }}</div>#}
</div>

{{ form_row(form.entryInventoryLines) }}
<div class="form-layout-footer mg-t-20">
    <button class="btn btn-primary bd-0" type="submit">Valider</button>
    <button class="btn btn-secondary bd-0" type="reset">Annuler</button>
</div><!-- form-layout-footer -->
{{ form_end(form) }}

templates/entry_inventory/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Inventaires{% endblock %}

{% block body %}
    <div class="slim-pageheader">
        <ol class="breadcrumb slim-breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('dashboard') }}">Tableau de bord</a></li>
            <li class="breadcrumb-item"><a href="{{ path('entry_inventory') }}">Les Inventaires</a></li>
            <li class="breadcrumb-item active" aria-current="page">Modifier entrées de stock</li>
        </ol>
        <h6 class="slim-pagetitle">Modifiation d'entrée de stock</h6>
    </div><!-- slim-pageheader -->
    <div class="section-wrapper">
        {{ include('entry_inventory/_form.html.twig') }}
    </div>

{% endblock %}
{% block javascripts %}

    <script src="{{ asset('assets/js/getResult.js') }}"></script>
    <script src="{{ asset('assets/js/entryInventory.js') }}"></script>
{% endblock %}

templates/entry_inventory/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Entrées de stock{% endblock %}

{% block body %}
    <div class="slim-pageheader">
        <ol class="breadcrumb slim-breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('dashboard') }}">Tableau de bord</a></li>
            <li class="breadcrumb-item"><a href="{{ path('entry_inventory') }}">Les Inventaires</a></li>
            <li class="breadcrumb-item active" aria-current="page">Liste des entrées de stock</li>
        </ol>
        <h6 class="slim-pagetitle">Les entrés de stock</h6>
    </div><!-- slim-pageheader -->

    <div class="section-wrapper">
        <div class="row">
            <div class="col-sm-10">
                <label class="section-title">Liste des entrées de stock </label>
            </div>
            <div class="col-sm-2">
                <a href="{{ path('entry_inventory_add') }}" class="btn btn-primary btn-block mg-b-10"><i class="fa fa-plus mg-r-2"></i> Nouveau</a>
            </div>
        </div>
        <p class="mg-b-20 mg-sm-b-40">Voici la liste complète des entrées de stock des produits de votre boutique</p>

        <div class="table-wrapper">
            <table id="user_data" class="table display responsive nowrap">
                <thead>
                <tr>
                    <th class="wd-10p">Id</th>
                    <th class="wd-15p">Référence</th>
                    <th class="wd-15p">Nbre de produits</th>
                    <th class="wd-10p">Qte Total</th>
                    <th class="wd-10p">Date</th>
                    <th class="wd-10p">Vendeur</th>
                    <th class="wd-15p">Action</th>
                </tr>
                </thead>
                <tbody>
                {% for entryInventory in data %}
                    <tr >
                        <td>
                            {{ entryInventory.id }}
                        </td>
                        <td>{{ entryInventory.reference }}</td>
                        <td>{{ entryInventory.entryInventoryLines | length }}</td>
                        <td>{{ entryInventory.totalQte }}</td>
                        <td>{{ entryInventory.createdAt  | date() }}</td>
                        <td>{{ entryInventory.author.fullName }}</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a class="btn btn-secondary" href="{{ path('entry_inventory_show', {'id': entryInventory.id}) }}"><i class="fa fa-eye"></i></a>
                                <a class="btn btn-secondary" href="{{ path('entry_inventory_edit', {'id': entryInventory.id}) }}"><i class="fa fa-pencil"></i></a>
                                <a class="btn btn-danger" href="{{ path('entry_inventory_delete', {'id': entryInventory.id}) }}" onclick="return confirm('Voulez vous vraiment supprimer la vente {{ entryInventory.reference }}')"><i class="fa fa-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div><!-- table-wrapper -->
    </div><!-- section-wrapper -->
{% endblock %}

{% block javascripts %}
    <script>
        $(function(){
            'use strict';

            $('#user_data').DataTable({
                bLengthChange: false,
                searching: true,
                responsive: true
            });

        });

        $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });
    </script>
{% endblock %}

templates/entry_inventory/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Inventaires{% endblock %}

{% block body %}
    <div class="slim-pageheader">
        <ol class="breadcrumb slim-breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('dashboard') }}">Tableau de bord</a></li>
            <li class="breadcrumb-item"><a href="{{ path('entry_inventory') }}">Les Inventaires</a></li>
            <li class="breadcrumb-item active" aria-current="page">Nouvelle entrée de stock</li>
        </ol>
        <h6 class="slim-pagetitle">Nouvelle entrée de stock</h6>
    </div><!-- slim-pageheader -->
    <div class="section-wrapper">
        {{ include('entry_inventory/_form.html.twig') }}
    </div>

{% endblock %}
{% block javascripts %}

    <script src="{{ asset('assets/js/getResult.js') }}"></script>
    <script src="{{ asset('assets/js/entryInventory.js') }}"></script>
{% endblock %}

templates/entry_inventory/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Inventaires{% endblock %}
{% block body %}
    <div class="slim-pageheader">
        <ol class="breadcrumb slim-breadcrumb">
            <li class="breadcrumb-item"><a href="#">Tableau de bord</a></li>
            <li class="breadcrumb-item"><a href="#">Les Entrées de stock</a></li>
            <li class="breadcrumb-item active" aria-current="page">Fiche de entrées de stock</li>
        </ol>
        <h6 class="slim-pagetitle">Détails de l'entrée en stock : {{ entryInventory.reference }}</h6>
    </div><!-- slim-pageheader -->
    <div class="section-wrapper">
        <div class="card card-invoice printableArea">
            <div  class="card-body">
                <div class="invoice-header">
                    <h1 class="invoice-title">Entrée en Stock</h1>
                    <div class="billed-from">
                        <h6>TAYBA MARKET</h6>
                        <p>201 Something St., Something Town, YT 242, Country 6546<br>
                            Tel No: 324 445-4544<br>
                            Email: youremail@companyname.com</p>
                    </div><!-- billed-from -->
                </div><!-- invoice-header -->

                <div class="row mg-t-20">
                    <div class="col-md">

                    </div><!-- col -->
                    <div class="col-md">
                        <label class="section-label-sm tx-gray-500">Fiche d'entrée en stock</label>
                        <p class="invoice-info-row">
                            <span>Entrée en stock No</span>
                            <span>{% if entryInventory.reference is not null %}{{ entryInventory.reference }} {% endif %}</span>
                        </p>
                        <p class="invoice-info-row">
                            <span>Date d'entrée:</span>
                            <span>{{ entryInventory.createdAt | date('d F Y H:i') }}</span>
                        </p>
                    </div><!-- col -->
                </div><!-- row -->

                <div class="table-responsive mg-t-40">
                    <table class="table table-invoice">
                        <thead>
                        <tr>
                            <th class="wd-20p">No</th>
                            <th class="wd-40p">Produit</th>
                            <th class="tx-center">Qte</th>
                            <th class="tx-right">Prix Unitaire</th>
                            <th class="tx-right">Montant</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for line in entryInventory.entryInventoryLines %}
                            <tr>
                                <td>{{ line.id }}</td>
                                <td class="tx-12">{{ line.product.name }}</td>
                                <td class="tx-center">{{ line.qte }}</td>
                                <td class="tx-right">{{ line.product.salePrice }}</td>
                                <td class="tx-right">{{ line.product.salePrice*line.qte }}</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td class="tx-right tx-uppercase tx-bold tx-inverse">Montant total</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td class="tx-right"><h4 class="tx-primary tx-bold tx-lato">{{ entryInventory.totalAmount }}</h4></td>
                        </tr>
                        </tbody>
                    </table>
                </div><!-- table-responsive -->

                <hr class="mg-b-60">

                <button id="print" class="btn btn-primary btn-block">Imprimer</button>

            </div><!-- card-body -->
        </div><!-- card -->

    </div><!-- section-wrapper -->
{% endblock %}