src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use function Symfony\Component\Form\remove;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[Vich\Uploadable]
#[ORM\HasLifecycleCallbacks]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message:"Le nom de produit  est obligatoire")]
    #[Assert\Length(min: 2,max: 255,minMessage: "Le nom doit être supérieur à 2 caractères", maxMessage: "Le nom doit être inférieur à 255 caractères")]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Assert\NotBlank(message:"La description du produit  est obligatoire")]
    private ?string $description = null;

    #[Vich\UploadableField(mapping: 'products', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $brandName = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message:"Le prix de vente du produit est obligatoire")]
    private ?int $salePrice = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message:"L'unité du produit est obligatoire")]
    private ?string $unit = null;

    #[ORM\Column(nullable: true)]
    #[Assert\NotBlank(message:"Le quantité seuil  du produit est obligatoire")]
    private ?int $minQte = null;

    #[ORM\Column(nullable: true)]
    #[Assert\NotBlank(message:"Le quantité initial disponible en stcok est obligatoire")]
    private ?int $initQte = null;

    #[ORM\Column(length: 55, nullable: true)]
    #[Assert\NotBlank(message:"Le code bar du produit est obligatoire")]
    private ?string $codeBar = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[Assert\NotBlank(message:"Le categorie (rayonnage) du produit est obligatoire")]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?User $author = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;


    #[ORM\OneToMany(mappedBy: 'product', targetEntity: OrderLine::class)]
    private Collection $orderLines;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: SaleLine::class)]
    private Collection $saleLines;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: EntryInventoryLine::class)]
    private Collection $entryInventoryLines;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: OutInventoryLine::class)]
    private Collection $outInventoryLines;

    public function __construct()
    {
        $this->saleLines = new ArrayCollection();
        $this->orderLines = new ArrayCollection();
        $this->entryInventoryLines = new ArrayCollection();
        $this->outInventoryLines = new ArrayCollection();
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initialize()
    {
        if(empty($this->createdAt)){
            $this->createdAt = new \DateTimeImmutable();
        }
        $this->updatedAt = new  \DateTimeImmutable();
    }

    public function getSaleQte()
    {
        $sum = array_reduce($this->saleLines->toArray(), function ($total, $saleLine){
            return $total + ($saleLine->getQte());
        }, 0);
        if(count($this->saleLines)>0){
            return $sum;
        }else{
            return 0;
        }
    }

    public function getOutStockQte()
    {
        $sum = array_reduce($this->outInventoryLines->toArray(), function ($total, $outInventoryLine){
            return $total + ($outInventoryLine->getQte());
        }, 0);
        if(count($this->outInventoryLines)>0){
            return $sum;
        }else{
            return 0;
        }
    }

    public function getInStockQte()
    {
        $sum = array_reduce($this->entryInventoryLines->toArray(), function ($total, $entryInventoryLine){
            return $total + ($entryInventoryLine->getQte());
        }, 0);
        if(count($this->entryInventoryLines)>0){
            return $sum;
        }else{
            return 0;
        }
    }

    public function getStockQte()
    {
        $sum = $this->initQte + $this->getInStockQte() - $this->getOutStockQte() - $this->getSaleQte();
        return $sum;
    }

    public function getStockValue()
    {
        return $this->getStockQte()*$this->salePrice;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName(): string
    {
        return $this->getName()." Fabriqué par :".$this->getBrandName();
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): static
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getBrandName(): ?string
    {
        return $this->brandName;
    }

    public function setBrandName(?string $brandName): static
    {
        $this->brandName = $brandName;

        return $this;
    }

    public function getSalePrice(): ?int
    {
        return $this->salePrice;
    }

    public function setSalePrice(?int $salePrice): static
    {
        $this->salePrice = $salePrice;

        return $this;
    }

    public function getUnit(): ?string
    {
        return $this->unit;
    }

    public function setUnit(?string $unit): static
    {
        $this->unit = $unit;

        return $this;
    }

    public function getMinQte(): ?int
    {
        return $this->minQte;
    }

    public function setMinQte(?int $minQte): static
    {
        $this->minQte = $minQte;

        return $this;
    }

    public function getInitQte(): ?int
    {
        return $this->initQte;
    }

    public function setInitQte(?int $initQte): static
    {
        $this->initQte = $initQte;

        return $this;
    }

    public function getCodeBar(): ?string
    {
        return $this->codeBar;
    }

    public function setCodeBar(?string $codeBar): static
    {
        $this->codeBar = $codeBar;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, SaleLine>
     */
    public function getSaleLines(): Collection
    {
        return $this->saleLines;
    }

    public function addSaleLine(SaleLine $saleLine): static
    {
        if (!$this->saleLines->contains($saleLine)) {
            $this->saleLines->add($saleLine);
            $saleLine->setProduct($this);
        }

        return $this;
    }

    public function removeSaleLine(SaleLine $saleLine): static
    {
        if ($this->saleLines->removeElement($saleLine)) {
            // set the owning side to null (unless already changed)
            if ($saleLine->getProduct() === $this) {
                $saleLine->setProduct(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->name; // Adjust this based on your entity's properties
    }

    /**
     * @return Collection<int, OrderLine>
     */
    public function getOrderLines(): Collection
    {
        return $this->orderLines;
    }

    public function addOrderLine(OrderLine $orderLine): static
    {
        if (!$this->orderLines->contains($orderLine)) {
            $this->orderLines->add($orderLine);
            $orderLine->setProduct($this);
        }

        return $this;
    }

    public function removeOrderLine(OrderLine $orderLine): static
    {
        if ($this->orderLines->removeElement($orderLine)) {
            // set the owning side to null (unless already changed)
            if ($orderLine->getProduct() === $this) {
                $orderLine->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, EntryInventoryLine>
     */

src/Entity/Sale.php
<?php

namespace App\Entity;

use App\Repository\SaleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SaleRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Sale
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 25, nullable: true)]
    private ?string $reference = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $saleAt = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $status = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $clientName = null;

    #[ORM\OneToMany(mappedBy: 'sale', targetEntity: SaleLine::class)]
    private Collection $saleLines;

    #[ORM\ManyToOne(inversedBy: 'sales')]
    private ?User $author = null;

    public function __construct()
    {
        $this->saleLines = new ArrayCollection();
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initialize()
    {
        if(empty($this->createdAt)){
            $this->createdAt = new \DateTimeImmutable();
            $this->saleAt = new \DateTimeImmutable();
        }
        $this->updatedAt = new  \DateTimeImmutable();
    }

    public function getAmount()
    {
        $sum = array_reduce($this->saleLines->toArray(), function ($total, $saleLine){
            return $total + ($saleLine->getQte()* $saleLine->getProduct()->getSalePrice());
        }, 0);
        if(count($this->saleLines) > 0){
            return $sum;
        }else{
            return 0;
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(?string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    public function getSaleAt(): ?\DateTimeImmutable
    {
        return $this->saleAt;
    }

    public function setSaleAt(?\DateTimeImmutable $saleAt): static
    {
        $this->saleAt = $saleAt;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getClientName(): ?string
    {
        return $this->clientName;
    }

    public function setClientName(?string $clientName): static
    {
        $this->clientName = $clientName;

        return $this;
    }

    /**
     * @return Collection<int, SaleLine>
     */
    public function getSaleLines(): Collection
    {
        return $this->saleLines;
    }

    public function addSaleLine(SaleLine $saleLine): static
    {
        if (!$this->saleLines->contains($saleLine)) {
            $this->saleLines->add($saleLine);
            $saleLine->setSale($this);
        }

        return $this;
    }

    public function removeSaleLine(SaleLine $saleLine): static
    {
        if ($this->saleLines->removeElement($saleLine)) {
            // set the owning side to null (unless already changed)
            if ($saleLine->getSale() === $this) {
                $saleLine->setSale(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }
}

src/Form/SaleType.php
<?php

namespace App\Form;

use App\Entity\Sale;
use App\Entity\SaleLine;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SaleType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            /*->add('reference', TextType::class, $this->getConfiguration('Référence',''))*/
            ->add('clientName', TextType::class, $this->getConfiguration('Nom du client',''))
            ->add('saleLines', CollectionType::class,$this->getConfiguration("", "",
                [
                'entry_type' => SaleLineType::class,
                'allow_add' => true,
                'allow_delete' => true
                ])
            )

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Sale::class,
        ]);
    }
}

templates/sale/_collection.html.twig
{% block _sale_saleLines_widget %}
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-bordered table-hover mg-b-0">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Code Bar</th>
                    <th>Nom du produit</th>
                    <th>Prix vente</th>
                    <th>Quantite</th>
                    <th>Montant</th>
                    <th class="text-right" colspan="2">
                        <button class="btn btn-primary bd-0" id="add-saleLine" type="button">Ajouter un produit</button>
                        <input type="hidden" id="widgets-counter" value="0">
                    </th>
                </tr>
                </thead>
                <tbody id="saleLine">
                {{ form_widget(form) }}
                </tbody>
            </table>
        </div>
    </div>

    {#<div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">
            <i class="fas fa-plus"></i>
            Ajouter une image
        </button>
    </div>#}
{% endblock %}

{% block _sale_saleLines_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _sale_saleLines_entry_widget %}
    {#<tr>
        <th colspan="7">{{ form_errors(form) }}</th>
    </tr>#}
    <tr class="sale-line" id="block_{{id}}">
        <th scope="row"><input type="hidden" value="{{ id }}"></th>
        <td class="code_bar">{{ form_widget(form.codeBar, {'attr':{'class': 'input-code-bar'}}) }}</td>
        <td>{{ form_widget(form.product, {'attr': {'class': 'select2-show-search'}}) }}</td>
        <td>{{ form_widget(form.stockQte, {'attr':{'disabled': 'disabled'}}) }}</td>
        <td>{{ form_widget(form.salePrice, {'attr':{'disabled': 'disabled'}}) }}</td>
        <td>{{ form_widget(form.qte) }}</td>
        <td>{{ form_widget(form.amount, {'attr':{'disabled': 'disabled'}}) }}</td>
        <td class="text-right">
            <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-outline-danger btn-icon">
                <div>
                    <i class="fa fa-trash-o"></i>
                </div>
            </button>
        </td>
    </tr>
{% endblock %}

templates/sale/_form.html.twig
{% form_theme form 'sale/_collection.html.twig' %}

{{ form_start(form) }}
<div class="row mg-b-25">
   {# <div class="col-lg-6">{{ form_row(form.reference) }}</div>#}
    <div class="col-lg-12">{{ form_row(form.clientName) }}</div>
</div>

{{ form_row(form.saleLines) }}
<div class="form-layout-footer mg-t-20">
    <button class="btn btn-primary bd-0" type="submit">Valider</button>
    <button class="btn btn-secondary bd-0" type="reset">Annuler</button>
</div><!-- form-layout-footer -->
{{ form_end(form) }}

templates/sale/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Ventes{% endblock %}

{% block body %}
    <div class="slim-pageheader">
        <ol class="breadcrumb slim-breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('dashboard') }}">Tableau de bord</a></li>
            <li class="breadcrumb-item"><a href="{{ path('sale') }}">Les ventes</a></li>
            <li class="breadcrumb-item active" aria-current="page">Modifier une vente</li>
        </ol>
        <h6 class="slim-pagetitle">Modifier la vente</h6>
    </div><!-- slim-pageheader -->
    <div class="section-wrapper">
        {{ include('sale/_form.html.twig') }}
    </div>

{% endblock %}
{% block javascripts %}

    <script src="{{ asset('assets/js/getResult.js') }}"></script>
    <script src="{{ asset('assets/js/sale.js') }}"></script>
{% endblock %}

templates/sale/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Ventes{% endblock %}

{% block body %}
    <div class="slim-pageheader">
        <ol class="breadcrumb slim-breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('dashboard') }}">Tableau de bord</a></li>
            <li class="breadcrumb-item"><a href="{{ path('sale') }}">Les ventes</a></li>
            <li class="breadcrumb-item active" aria-current="page">Liste des ventes</li>
        </ol>
        <h6 class="slim-pagetitle">Les ventes</h6>
    </div><!-- slim-pageheader -->

    <div class="section-wrapper">
        <div class="row">
            <div class="col-sm-10">
                <label class="section-title">Liste des ventes </label>
            </div>
            <div class="col-sm-2">
                <a href="{{ path('sale_add') }}" class="btn btn-primary btn-block mg-b-10"><i class="fa fa-plus mg-r-2"></i> Nouveau</a>
            </div>
        </div>
        <p class="mg-b-20 mg-sm-b-40">Voici la liste complète des produits disponible dans votre boutique</p>

        <div class="table-wrapper">
            <table id="user_data" class="table display responsive nowrap">
                <thead>
                <tr>
                    <th class="wd-10p">Id</th>
                    <th class="wd-15p">Référence</th>
                    <th class="wd-15p">Client</th>
                    <th class="wd-10p">Montant Total</th>
                    <th class="wd-10p">Date</th>
                    <th class="wd-10p">Vendeur</th>
                    <th class="wd-15p">Action</th>
                </tr>
                </thead>
                <tbody>
                {% for sale in data %}
                    <tr >
                        <td>
                            {{ sale.id }}
                        </td>
                        <td>{{ sale.reference }}</td>
                        <td>{{ sale.clientName }}</td>
                        <td>{{ sale.amount }}</td>
                        <td>{{ sale.saleAt | date() }}</td>
                        <td>{{ sale.author.fullName }}</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a class="btn btn-secondary" href="{{ path('sale_show', {'id': sale.id}) }}"><i class="fa fa-eye"></i></a>
                                <a class="btn btn-secondary" href="{{ path('sale_edit', {'id': sale.id}) }}"><i class="fa fa-pencil"></i></a>
                                <a class="btn btn-danger" href="{{ path('sale_delete', {'id': sale.id}) }}" onclick="return confirm('Voulez vous vraiment supprimer la vente {{ sale.reference }}')"><i class="fa fa-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div><!-- table-wrapper -->
    </div><!-- section-wrapper -->
{% endblock %}

{% block javascripts %}
    <script>
        $(function(){
            'use strict';

            $('#user_data').DataTable({
                bLengthChange: false,
                searching: true,
                responsive: true
            });

        });

        $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });
    </script>
{% endblock %}

templates/sale/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Ventes{% endblock %}

{% block body %}
    <div class="slim-pageheader">
        <ol class="breadcrumb slim-breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('dashboard') }}">Tableau de bord</a></li>
            <li class="breadcrumb-item"><a href="{{ path('sale') }}">Les ventes</a></li>
            <li class="breadcrumb-item active" aria-current="page">Ajouter une vente</li>
        </ol>
        <h6 class="slim-pagetitle">Nouvelle vente</h6>
    </div><!-- slim-pageheader -->
    <div class="section-wrapper">
        {{ include('sale/_form.html.twig') }}
    </div>

{% endblock %}

{% block javascripts %}

    <script src="{{ asset('assets/js/getResult.js') }}"></script>
    <script src="{{ asset('assets/js/sale.js') }}"></script>
    {#<script src="{{ asset('assets/lib/select2/js/select2.full.min.js') }}"></script>#}
    <script>
        // Select2 by showing the search
        $('.select2-show-search').select2({
            minimumResultsForSearch: ''
        });
    </script>
{% endblock %}

{% block stylesheets %}
    {#<link href="{{ asset('assets/lib/select2/css/select2.min.css') }}" rel="stylesheet">#}
{% endblock %}

templates/sale/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Ventes{% endblock %}
{% block body %}
    <div class="slim-pageheader">
        <ol class="breadcrumb slim-breadcrumb">
            <li class="breadcrumb-item"><a href="#">Tableau de bord</a></li>
            <li class="breadcrumb-item"><a href="#">Les Ventes</a></li>
            <li class="breadcrumb-item active" aria-current="page">Fiche de ventes</li>
        </ol>
        <h6 class="slim-pagetitle">Détails de la vente : {{ sale.reference }}</h6>
    </div><!-- slim-pageheader -->
    <div class="section-wrapper">
        <div class="card card-invoice printableArea">
            <div  class="card-body">
                <div class="invoice-header">
                    <h1 class="invoice-title">Facture</h1>
                    <div class="billed-from">
                        <h6>TAYBA MARKET</h6>
                        <p>201 Something St., Something Town, YT 242, Country 6546<br>
                            Tel No: 324 445-4544<br>
                            Email: youremail@companyname.com</p>
                    </div><!-- billed-from -->
                </div><!-- invoice-header -->

                <div class="row mg-t-20">
                    <div class="col-md">
                        <label class="section-label-sm tx-gray-500">Reçu de vente à</label>
                        <div class="billed-to">
                            <h6 class="tx-gray-800">{% if sale.clientName is not null %}{{ sale.clientName }}{% endif %}</h6>
                        </div>
                    </div><!-- col -->
                    <div class="col-md">
                        <label class="section-label-sm tx-gray-500">Information sur la facture</label>
                        <p class="invoice-info-row">
                            <span>Facture No</span>
                            <span>{% if sale.reference is not null %}{{ sale.reference }} {% endif %}</span>
                        </p>
                        <p class="invoice-info-row">
                            <span>Date de la vente:</span>
                            <span>{{ sale.createdAt | date('d F Y H:i') }}</span>
                        </p>
                        <p class="invoice-info-row">
                            <span>Date du Paiement:</span>
                            <span>{{ sale.saleAt | date('d F Y H:i') }}</span>
                        </p>
                    </div><!-- col -->
                </div><!-- row -->

                <div class="table-responsive mg-t-40">
                    <table class="table table-invoice">
                        <thead>
                        <tr>
                            <th class="wd-20p">No</th>
                            <th class="wd-40p">Produit</th>
                            <th class="tx-center">Qte</th>
                            <th class="tx-right">Prix Unitaire</th>
                            <th class="tx-right">Montant</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for saleLine in sale.saleLines %}
                        <tr>
                            <td>{{ saleLine.id }}</td>
                            <td class="tx-12">{{ saleLine.product.name }}</td>
                            <td class="tx-center">{{ saleLine.qte }}</td>
                            <td class="tx-right">{{ saleLine.product.salePrice }}</td>
                            <td class="tx-right">{{ saleLine.product.salePrice*saleLine.qte }}</td>
                        </tr>
                        {% endfor %}

                        <tr>
                            <td class="tx-right">Tax (5%)</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td  class="tx-right">$287.50</td>
                        </tr>
                        <tr>
                            <td class="tx-right">Discount</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td class="tx-right">-$50.00</td>
                        </tr>
                        <tr>
                            <td class="tx-right tx-uppercase tx-bold tx-inverse">Total Due</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td class="tx-right"><h4 class="tx-primary tx-bold tx-lato">{{ sale.amount }}</h4></td>
                        </tr>
                        </tbody>
                    </table>
                </div><!-- table-responsive -->

                <hr class="mg-b-60">

                <button id="print" class="btn btn-primary btn-block">Imprimer</button>

            </div><!-- card-body -->
        </div><!-- card -->
    </div><!-- section-wrapper -->
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('assets/js/jquery.PrintArea.js') }}" type="text/JavaScript"></script>
    <script>
        $(document).ready(function() {
            $("#print").click(function() {
                var mode = 'iframe'; //popup
                var close = mode == "popup";
                var options = {
                    mode: mode,
                    popClose: close
                };
                $("div.printableArea").printArea(options);
            });
        });
    </script>
{% endblock %}