src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use function Symfony\Component\Form\remove;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[Vich\Uploadable]
#[ORM\HasLifecycleCallbacks]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message:"Le nom de produit  est obligatoire")]
    #[Assert\Length(min: 2,max: 255,minMessage: "Le nom doit être supérieur à 2 caractères", maxMessage: "Le nom doit être inférieur à 255 caractères")]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Assert\NotBlank(message:"La description du produit  est obligatoire")]
    private ?string $description = null;

    #[Vich\UploadableField(mapping: 'products', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $brandName = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message:"Le prix de vente du produit est obligatoire")]
    private ?int $salePrice = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message:"L'unité du produit est obligatoire")]
    private ?string $unit = null;

    #[ORM\Column(nullable: true)]
    #[Assert\NotBlank(message:"Le quantité seuil  du produit est obligatoire")]
    private ?int $minQte = null;

    #[ORM\Column(nullable: true)]
    #[Assert\NotBlank(message:"Le quantité initial disponible en stcok est obligatoire")]
    private ?int $initQte = null;

    #[ORM\Column(length: 55, nullable: true)]
    #[Assert\NotBlank(message:"Le code bar du produit est obligatoire")]
    private ?string $codeBar = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[Assert\NotBlank(message:"Le categorie (rayonnage) du produit est obligatoire")]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?User $author = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;


    #[ORM\OneToMany(mappedBy: 'product', targetEntity: OrderLine::class)]
    private Collection $orderLines;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: SaleLine::class)]
    private Collection $saleLines;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: EntryInventoryLine::class)]
    private Collection $entryInventoryLines;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: OutInventoryLine::class)]
    private Collection $outInventoryLines;

    public function __construct()
    {
        $this->saleLines = new ArrayCollection();
        $this->orderLines = new ArrayCollection();
        $this->entryInventoryLines = new ArrayCollection();
        $this->outInventoryLines = new ArrayCollection();
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initialize()
    {
        if(empty($this->createdAt)){
            $this->createdAt = new \DateTimeImmutable();
        }
        $this->updatedAt = new  \DateTimeImmutable();
    }

    public function getSaleQte()
    {
        $sum = array_reduce($this->saleLines->toArray(), function ($total, $saleLine){
            return $total + ($saleLine->getQte());
        }, 0);
        if(count($this->saleLines)>0){
            return $sum;
        }else{
            return 0;
        }
    }

    public function getOutStockQte()
    {
        $sum = array_reduce($this->outInventoryLines->toArray(), function ($total, $outInventoryLine){
            return $total + ($outInventoryLine->getQte());
        }, 0);
        if(count($this->outInventoryLines)>0){
            return $sum;
        }else{
            return 0;
        }
    }

    public function getInStockQte()
    {
        $sum = array_reduce($this->entryInventoryLines->toArray(), function ($total, $entryInventoryLine){
            return $total + ($entryInventoryLine->getQte());
        }, 0);
        if(count($this->entryInventoryLines)>0){
            return $sum;
        }else{
            return 0;
        }
    }

    public function getStockQte()
    {
        $sum = $this->initQte + $this->getInStockQte() - $this->getOutStockQte() - $this->getSaleQte();
        return $sum;
    }

    public function getStockValue()
    {
        return $this->getStockQte()*$this->salePrice;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName(): string
    {
        return $this->getName()." Fabriqué par :".$this->getBrandName();
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): static
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getBrandName(): ?string
    {
        return $this->brandName;
    }

    public function setBrandName(?string $brandName): static
    {
        $this->brandName = $brandName;

        return $this;
    }

    public function getSalePrice(): ?int
    {
        return $this->salePrice;
    }

    public function setSalePrice(?int $salePrice): static
    {
        $this->salePrice = $salePrice;

        return $this;
    }

    public function getUnit(): ?string
    {
        return $this->unit;
    }

    public function setUnit(?string $unit): static
    {
        $this->unit = $unit;

        return $this;
    }

    public function getMinQte(): ?int
    {
        return $this->minQte;
    }

    public function setMinQte(?int $minQte): static
    {
        $this->minQte = $minQte;

        return $this;
    }

    public function getInitQte(): ?int
    {
        return $this->initQte;
    }

    public function setInitQte(?int $initQte): static
    {
        $this->initQte = $initQte;

        return $this;
    }

    public function getCodeBar(): ?string
    {
        return $this->codeBar;
    }

    public function setCodeBar(?string $codeBar): static
    {
        $this->codeBar = $codeBar;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, SaleLine>
     */
    public function getSaleLines(): Collection
    {
        return $this->saleLines;
    }

    public function addSaleLine(SaleLine $saleLine): static
    {
        if (!$this->saleLines->contains($saleLine)) {
            $this->saleLines->add($saleLine);
            $saleLine->setProduct($this);
        }

        return $this;
    }

    public function removeSaleLine(SaleLine $saleLine): static
    {
        if ($this->saleLines->removeElement($saleLine)) {
            // set the owning side to null (unless already changed)
            if ($saleLine->getProduct() === $this) {
                $saleLine->setProduct(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->name; // Adjust this based on your entity's properties
    }

    /**
     * @return Collection<int, OrderLine>
     */
    public function getOrderLines(): Collection
    {
        return $this->orderLines;
    }

    public function addOrderLine(OrderLine $orderLine): static
    {
        if (!$this->orderLines->contains($orderLine)) {
            $this->orderLines->add($orderLine);
            $orderLine->setProduct($this);
        }

        return $this;
    }

    public function removeOrderLine(OrderLine $orderLine): static
    {
        if ($this->orderLines->removeElement($orderLine)) {
            // set the owning side to null (unless already changed)
            if ($orderLine->getProduct() === $this) {
                $orderLine->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, EntryInventoryLine>
     */

src/Controller/StockController.php
<?php

namespace App\Controller;

use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class StockController extends AbstractController
{
    #[Route('/stock', name: 'stock')]
    public function index(ProductRepository $repository): Response
    {
        $data = $repository->findBy([], ['createdAt' => 'DESC'], null, null);
        $sum = array_reduce($data, function ($total, $product){
            return $total + ($product->getStockValue());
        }, 0);

        return $this->render('stock/index.html.twig', [
            'data' => $data,
            'StockValue' =>  $sum,
        ]);
    }
}

templates/stock/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etat du stock{% endblock %}

{% block body %}
    <div class="slim-pageheader">
        <ol class="breadcrumb slim-breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('dashboard') }}">Tableau de bord</a></li>
            <li class="breadcrumb-item"><a href="{{ path('stock') }}">Etat du stock</a></li>
            <li class="breadcrumb-item active" aria-current="page">Fiche de stock au : {{ "now" | date('d F Y H:i') }}</li>
        </ol>
        <h6 class="slim-pagetitle">Etat du stock au : {{ "now" | date('d F Y H:i') }}</h6>
    </div><!-- slim-pageheader -->
    <div class="section-wrapper">
        <div class="card card-invoice printableArea">
            <div  class="card-body">
                <div class="invoice-header">
                    <h1 class="invoice-title">Etat du stock</h1>
                    <div class="billed-from">
                        <h6>TAYBA MARKET</h6>
                        <p>201 Something St., Something Town, YT 242, Country 6546<br>
                            Tel No: 324 445-4544<br>
                            Email: youremail@companyname.com</p>
                    </div><!-- billed-from -->
                </div><!-- invoice-header -->

                <div class="row mg-t-20">
                    <div class="col-md">

                    </div><!-- col -->
                    <div class="col-md">
                        <label class="section-label-sm tx-gray-500">Information sur le stock</label>

                        <p class="invoice-info-row">
                            <span>Etat de la commande:</span>
                            <span>{{ "now"| date('d F Y à H:i')}}}</span>
                        </p>
                    </div><!-- col -->
                </div><!-- row -->

                <div class="table-responsive mg-t-40">
                    <table class="table table-invoice">
                        <thead>
                        <tr>
                            <th class="wd-5p">No</th>
                            <th class="wd-40p">Produit</th>
                            <th class="tx-center">Qte Initiale</th>
                            <th class="tx-center">Qte vendue</th>
                            <th class="tx-center">Qte sortie</th>
                            <th class="tx-center">Qte entrée</th>
                            <th class="tx-center">Qte minilale</th>
                            <th class="tx-center">Qte Disponible</th>
                            <th class="tx-center">Prix Unitaire</th>
                            <th class="tx-center">Valeur total</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for product in data %}
                            <tr>
                                <td>{{ product.id }}</td>
                                <td class="tx-12">{{ product.name }}</td>
                                <td class="tx-center">{{ product.initQte }}</td>
                                <td class="tx-center">{{ product.saleQte }}</td>
                                <td class="tx-center">{{ product.outStockQte }}</td>
                                <td class="tx-center">{{ product.inStockQte  }}</td>
                                <td class="tx-center">{{ product.minQte }}</td>
                                <td class="tx-center">{{ product.stockQte }}</td>
                                <td class="tx-right">{{ product.salePrice }}</td>
                                <td class="tx-right">{{ product.stockValue }}</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td colspan="9" class="tx-left tx-uppercase tx-bold tx-inverse">Valeur total du stock</td>

                            <td class="tx-right"><h4 class="tx-primary tx-bold tx-lato">{{ StockValue }}</h4></td>
                        </tr>
                        </tbody>
                    </table>
                </div><!-- table-responsive -->

                <hr class="mg-b-60">

                <button id="print" class="btn btn-primary btn-block">Imprimer</button>

            </div><!-- card-body -->
        </div><!-- card -->

    </div><!-- section-wrapper -->
{% endblock %}